# Generated by Django 5.2.8 on 2026-01-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='currency',
            field=models.CharField(choices=[('₦', 'NGN - Nigerian Naira'), ('$', 'USD - US Dollar'), ('€', 'EUR - Euro'), ('£', 'GBP - British Pound'), ('¥', 'JPY - Japanese Yen'), ('GH₵', 'GHS - Ghanaian Cedi')], default='₦', max_length=5),
        ),
    ]
