# Generated by Django 5.2.8 on 2026-01-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_property_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='currency',
            field=models.CharField(choices=[('₦', 'NGN - Nigerian Naira'), ('$', 'USD - US Dollar'), ('€', 'EUR - Euro'), ('£', 'GBP - British Pound'), ('C$', 'CAD - Canadian Dollar'), ('¥', 'JPY - Japanese Yen'), ('GH₵', 'GHS - Ghanaian Cedi')], default='₦', max_length=5),
        ),
    ]
