# Generated by Django 5.2.8 on 2026-06-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_property_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, upload_to='agents/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='main_photo',
            field=models.ImageField(blank=True, max_length=255, upload_to='properties/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(max_length=255, upload_to='properties/extra/%Y/%m/%d'),
        ),
    ]
