# Generated by Django 5.2.8 on 2026-01-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='role_type',
            field=models.CharField(choices=[('Executive', 'Executive Leadership'), ('Management', 'Senior Management & Key Personnel')], default='Management', max_length=20),
        ),
    ]
