# Generated by Django 5.2.8 on 2026-06-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_teammember_role_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, upload_to='team/%Y/%m'),
        ),
    ]
