# Generated by Django 5.2.8 on 2025-12-01 12:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('author', models.CharField(default='URC Staff', max_length=100)),
                ('body', models.TextField()),
                ('cover_image', models.ImageField(blank=True, upload_to='publications/%Y/%m/')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Articles & Publications',
                'ordering': ('-publish_date',),
            },
        ),
    ]
