# Generated by Django 5.2.8 on 2026-01-16 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('publish_date',), 'verbose_name_plural': 'Articles & Publications'},
        ),
    ]
