# Generated by Django 5.2.8 on 2026-06-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_alter_article_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=255, upload_to='publications/%Y/%m/'),
        ),
    ]
